# Generated by Django 5.1.7 on 2025-03-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='schedule',
            new_name='schedule_id',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='studentyearlevel',
            old_name='yearlevel',
            new_name='yearlevel_id',
        ),
    ]
